### ISSUE TITLE
[FEATURE] Add location to in-person events

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#4132]
### Description

Maybe we could add a location to the in person events?

<img width="1284" alt="Screenshot 2023-01-27 at 11 49 42 PM" src="https://user-images.githubusercontent.com/51131670/215164522-c3edeb58-d5de-4444-91dc-55366afed58b.png">

**Comment by Pradumnasaraf** [comment]
Great point. Later with that data, we can also add those to the live map to see which conferences are happing nearby.

**Comment by ShuvamChatterjee28** [comment]
Can I try to do this one please @ChinmayMhatre and @Pradumnasaraf?

**Comment by Vishrut19** [comment]
Hey ! Can I try to work on this issue ? @Pradumnasaraf

**Comment by eddiejaoude** [comment]
I think the data we need to capture is...

```js
"location": {
   "road": "",
   "city": "",
   "state": "",
   "country": ""
}
```

Please add to the docs also

**Comment by Vishrut19** [comment]
> I think the data we need to capture is...
> 
> ```js
> "location": {
>    "road": "",
>    "city": "",
>    "state": "",
>    "country": ""
> }
> ```
> 
> Please add to the docs also

okay @eddiejaoude I got some idea about it. Where can I discuss about it with you ?

**Comment by ShuvamChatterjee28** [comment]
Hey @eddiejaoude, can you kindly assign me?

**Comment by Mutai-Gilbert** [comment]
Hello @eddiejaoude, I'll be so happy to work on this issue. Kindly let me work on this.

**Comment by ChinmayMhatre** [comment]
> Can I try to do this one please @ChinmayMhatre and @Pradumnasaraf?

Hey @ShuvamChatterjee28 I can't assign it to you. But you can go ahead with this. If you want any help let us know. Thank you!

**Comment by Pradumnasaraf** [comment]
Hey, @ShuvamChatterjee28 you can go ahead and others, please look for other issues. 

Thank you!

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf! @ShuvamChatterjee28 is already assigned and working on an issue i.e. issue number #4223. You can have a look at it.

**Comment by ShuvamChatterjee28** [comment]
For #4223, the PR is created. Thanks. Working on this issue now.

**Comment by Pradumnasaraf** [comment]
Hey, @ShuvamChatterjee28,

@ShuvamChatterjee28 commented on the issue 1st, this is why they are been assigned. Also, I didn't know that they are already assigned to an issue, and people can work on 1-2 issues together. 

You can look for other open issues.

**Comment by Vishrut19** [comment]
Cool no problem @Pradumnasaraf and also I have found an issue. Where can I raise it ?

**Comment by Pradumnasaraf** [comment]
> Cool no problem @Pradumnasaraf and also I have found an issue. Where can I raise it ?

Here - https://github.com/EddieHubCommunity/LinkFree/issues/new/choose

**Comment by ShuvamChatterjee28** [comment]
Hey @Pradumnasaraf and @eddiejaoude, I have made a working prototype of the location parameter in events. Also I have updated the docs too. Please have a look at the screenshot and let me know if you like it or not --> 
<img width="1140" alt="Screenshot 2023-02-01 at 9 52 21 PM" src="https://user-images.githubusercontent.com/38078961/216102566-8600e009-5c78-4aff-9c8e-88108d04d25f.png">
(The Docs containing the `location` parameter. Now all the required flags are false, because I have set the code like, **if isVirtual is set as true && isInPerson is false**, then by fault the location will be remote)

<img width="1426" alt="Screenshot 2023-02-01 at 10 03 59 PM" src="https://user-images.githubusercontent.com/38078961/216104878-0a34681a-5f3d-4bbd-950c-ed16d57ade84.png">
(It is the layout of the events page containing the location)

Please suggest, if I should make any changes in the layout or not!

**Comment by ChinmayMhatre** [comment]
Hey @ShuvamChatterjee28 , I think it would be best if you created a PR with your solution. The changes could be discussed over on the PR. Thanks

**Comment by ShuvamChatterjee28** [comment]
Got it @ChinmayMhatre, will create a PR. Thanks.

**Comment by Pradumnasaraf** [comment]
Yes, you can raise a draft PR!

**Comment by saaagarsingh** [comment]
Hey @ShuvamChatterjee28 just had a doubt what if event is in hybrid mode??? The logic will still show remote.

**Comment by ShuvamChatterjee28** [comment]
Nope, it is updated now.

**Comment by ashutosh887** [comment]
@eddiejaoude  I would like to work on this

**Comment by eddiejaoude** [comment]
@ashutosh887 please read the history of the issue timeline, you will see it is already assigned and a pull request has already been created. 

Please have a look the issue list and select an issue that
- is not already assigned (unless more than 2 weeks with no activity and we can reassign it)
- has no existing pul request
- also the issue has the label `status: ready for dev`

**Comment by ashutosh887** [comment]
Thanks @eddiejaoude 
I'll keep this in mind

**Comment by eddiejaoude** [comment]
This PR has been merged
