### ISSUE TITLE
Update UI fixes in Search bar

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/LinkFree#5828]
### Description

There should be some Margin and Padding between the suggestion notification buttons to the next button ,There should be some gap between them. it looks like the buttons are been touched ,looking not so good the red and white buttons.

### Screenshots

![linkfree](https://user-images.githubusercontent.com/111564362/229690121-8c29872b-1983-4c57-b7b1-fbb41db13f03.jpg)

### Additional information

We can do a thing that we increase the margin and padding between them .

**Comment by bharathkalyans** [comment]
yeah it needs a bit of margin between the tags!

**Comment by bharathkalyans** [comment]
Added Spacing to the Elements.Below is the snapshot. Please let me know if there are any other changes, else I can PR.
<img width="1552" alt="Screenshot 2023-04-04 at 11 24 49 AM" src="https://user-images.githubusercontent.com/49526472/229700231-5d305244-d68c-4a40-bdb3-61c066854fc6.png">

**Comment by bharathkalyans** [comment]
Fixed the positioning of the Badges as well. The Outcome looks something similar 
to the below snapshot.

<img width="1552" alt="Screenshot 2023-04-04 at 11 51 55 AM" src="https://user-images.githubusercontent.com/49526472/229705437-a6142e13-1b83-4d39-a31b-ce925d2a7b82.png">

**Comment by bharathkalyans** [comment]
@eddiejaoude Can you please look into this PR.

**Comment by eddiejaoude** [comment]
I will reopen the issue if the PR is still open

**Comment by eddiejaoude** [comment]
This issue is still awaiting triage, and is not ready for development

**Comment by eddiejaoude** [comment]
I am only opening an exception this once, please in future please read the project's contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Also note, the maintainers get notified of new issues and pull requests, it is not appropriate to chase 10mins after, especially as we are all in different timezones

**Comment by eddiejaoude** [comment]
It is now merged and this issue is closed. Thank you for your contribution, we do have more urgent contributions that would be welcome 👍
